### ISSUE TITLE
Build failed :  dependency cycle

### ISSUE THREAD

**Issue by thinkneu** [roboticslibrary/libiconv#1] opened 2020-06-26 15:27 UTC
I am trying to build the lib using cmake as the following:
- cd libiconv
- mkdir build
- cd build
- cmake .. -G Ninja
- ninja

 It keeps getting the message : 
- ninja: error: dependency cycle: lib/aliases.gperf.h -> lib/aliases.gperf.h

Any help ?
Thank you.

**Comment by rickertm** [comment] 2020-06-26 17:00
Thank you for finding this issue, I was able to reproduce this on an older CMake version. Recent CMake versions seem to work fine, but the older one (3.5.1 in Ubuntu 16.04) seems to have confused `lib/aliases.gperf` with `lib/aliases.gperf.h`, maybe due to the additional dot. This should now be fixed in https://github.com/roboticslibrary/libiconv/commit/a7ca9a1f01dd6988543133ebc9015338c54268ca.

**Comment by thinkneu** [comment] 2020-06-27 16:09
Thank you very much. The problem is now fixed, and it compiles fine.
However, may i ask what is gperf used for ? from what i see, it is needed to build the library ?
Also the libiconv read-me file tells that it has circular dependency on gnu gettext ? where is that?

**Comment by rickertm** [comment] 2020-06-27 18:51
I'm glad to hear this fixed your issue.

libiconv uses gperf during the build process to generate hash functions and tables, e.g., for generating the file `aliases.h`, `aliases_aix.h` etc. When using autotools, this is done in `Makefile.devel` and the generated files are included in the release tarball:
https://github.com/roboticslibrary/libiconv/blob/4d2b066e470566fa6abfbbcb78d1e45042b40158/Makefile.devel#L118-L126

According to the readme, only the iconv program uses gettext for internationalization and there is a corresponding include in `iconv.c`, while the libiconv library does not seem to have any dependencies on it:
https://github.com/roboticslibrary/libiconv/blob/4d2b066e470566fa6abfbbcb78d1e45042b40158/src/iconv.c#L73-L75
The iconv program requires Gnulib, therefore a cross-platform build is currently not easily possible as various header files are not supported on Windows/MSVC.

**Comment by thinkneu** [comment] 2020-06-27 19:55
I really appreciate your answer, thank you very much. i understand now. 
One last question, In a project i am working on, i have to build, distribute and use libiconv on systems on which neither libiconv or gperf are available, then came the need to build them manually as a part of the build process. 
I tried to make the following cmake configuration :

Project dir : 
- src dir
- external_libs dir
- cmakelists.txt 

The top level cmake add the src and external_libs directories. 
the external_libs contain  : 
- gperf-cmake-branch 
- libiconv-cmake-branch
- cmakelists.txt

literally the cmake file contains :
add_subdirectory(gperf-cmake-branch)
add_subdirectory(libiconv-cmake-branch)

I added gperf before libiconv to provide the build gperf dependancy firtst then build libiconv.  
On building i keep getting the error : 

Make Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Gperf (missing: GPERF_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGperf.cmake:7 (find_package_handle_standard_args)
  CMakeLists.txt:42 (find_package)
-- Configuring incomplete, errors occurred!

I know this is not right cmake-wise, but i can not think of a solution for this. I am not expert in cmake. 
I am really grateful for your help.

Thank you in advance.

**Comment by rickertm** [comment] 2020-06-28 16:16
I have added a [config file and exported targets](https://github.com/roboticslibrary/gperf/commit/7a08f592c6b4752438a7a679ca9ab5fc2c81e4b1) to gperf as well as a [matching alias](https://github.com/roboticslibrary/gperf/commit/8cd8f9417ee25608afdccc9e73327524a2e17ecd) and updated libiconv to check for an existing [target and a config file](https://github.com/roboticslibrary/libiconv/commit/524379ebfea5b0f10303246d85b610528b1d6d8e). This should now enable libiconv to use the gperf target in your subdirectory.

You can also have a look at CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) module as an alternative to `add_subdirectory()`.

**Comment by thinkneu** [comment] 2020-06-29 06:58
You are awesome. Thank you. My previous configuration really worked thanks to your last commit.
I was just reading about FetchContent and ExternalProject. I will further read about them. Any way your commits just did the math. Thank you very much.

**Closed as completed** 2020-07-01 22:27 UTC
